### ISSUE TITLE
How to concatenate several wav files?

### ISSUE THREAD

**Issue by gotclout** [cryptix/wav#13]
There was an issue posted previously, but the OP decided to use mp3 so How to concatenate several wav files? #6 was closed.

If there is a solution to the header problem mentioned in the approach of the OP. Please advise, or provide an alternate solution.

ref: https://github.com/cryptix/wav/issues/6

**Comment by cryptix** [comment]
Can you elaborate on your concrete problem and maybe share examples?

In general it should be possible to create two wav readers and play them into a new writer.
If the files are small enough, I would advice not to use _dumb read/writer_ but `r.ReadSample()` and `w.WriteSample`.

**Comment by gotclout** [comment]
This solution makes sense, I was concerned that the mechanism in the previous pay would not have accurate header information, or require the header to be updated manually. I will try your suggestion.

**Comment by gotclout** [comment]
Ok, this works if I use reader.ReadRawSample and writer.WriteSample. Using reader.ReadSample with writer.WriteInt32 causes an error working with stereo channels. I forked and enabled file.Channels = 1 or 2 in writer.go

https://github.com/gotclout/wav/blob/master/examples/wavConcat/concat.go

k,thx,bye
 ^_^
