### ISSUE TITLE
Obtain header data of wav

### ISSUE THREAD

**Issue by medakk** [cryptix/wav#19]
I need to obtain the sample rate, number of channels and the bits per sample in order to play  the read audio file in my program, but these values are not exposed by the API. However they are printed in the String function:
```
	// chunk fmt
	msg += fmt.Sprintf("Audio format      : %d\n", wav.chunkFmt.AudioFormat)
	msg += fmt.Sprintf("Number of channels: %d\n", wav.chunkFmt.NumChannels)
	msg += fmt.Sprintf("Sampling rate     : %d Hz\n", wav.chunkFmt.SampleRate)
	msg += fmt.Sprintf("Sample size       : %d bits\n", wav.chunkFmt.BitsPerSample)
```

Is there any reason this cannot be added to the public API? 
I'll make a PR for it if not.

**Comment by cryptix** [comment]
A PR would be very welcome. :)
